version: '3.5'

services:
  backend:
    image: node:latest
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    working_dir: /app
    command: bash -c "npm i && npm start"

  frontend:
    image: node:latest
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: bash -c "npm i && npm start"
